apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-frontend
  namespace: genai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: genai-frontend
  template:
    metadata:
      labels:
        app: genai-frontend
    spec:
      containers:
      - name: genai-frontend
        image: dhaprako/genai-frontend:v1
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: genai-frontend-config
              key: NEXT_PUBLIC_API_BASE_URL
